version: "3"
services:

  identidock:
    # image: identidock
    build: .
    ports:
      - 8080:5000
    environment:
      ENV: DEV
    volumes:
      - ./app:/app

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis:latest
